### ISSUE TITLE
[Issue/Request] Two messages PF2e

### ISSUE THREAD

**Issue by roguedevjake** [cs96and/FoundryVTT-damage-log#24] opened 2022-10-29 12:50 UTC
PF2e has a native /damage log lite/ of sorts, it only triggers off the usage of the damage buttons (not any other hp alteration)  and has no undo function. 

Unfortunately you can only set its flag as visible to everyone or visible to GM only in the system. 

My request, have damage-log set the PF2e messages to be hidden to all when installed by default.

[Image showing the issue](https://imgur.com/a/F1B9oyo) (red shaded is my css adjusted damage-log module entry to save on space due to the double messages)

**Comment by cs96and** [comment] 2022-10-29 12:57
Duplicate of #19

Unfortunately this is not doable without changes to the pf2e system

**Closed** 2022-10-29 12:57 UTC
