### ISSUE TITLE
Feature Request - Smaller icons

### ISSUE THREAD

**Issue by ChobitsCrazy** [cs96and/FoundryVTT-damage-log#48] opened 2024-06-14 19:15 UTC
Hey love the mod, this has replaced the Heath Monitor mod for me.
Would like to see a toggle setting to have the actor portrait icon show as a smaller image instead of larger one. Similar to how the chat portraits are.

**Comment by cs96and** [comment] 2024-07-05 22:05
Duplicate of #47

**Closed by cs96and** 2024-07-05 22:05 UTC
